#!/usr/bin/env bash
# install.sh — One-command bootstrap for Forum Operating System.
#
# Usage (from anywhere):
#   curl -sSL https://raw.githubusercontent.com/hipolitogb/forum-eos-operation-system/main/install.sh | bash
#
# Or with tunables:
#   INSTALL_DIR=/srv/forum APP_PORT=8080 bash install.sh
#
# Requirements: docker + docker compose plugin.
# Pulls the pre-built image from GHCR (no source code needed on the host).

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$PWD/forum}"
IMAGE="${IMAGE:-ghcr.io/hipolitogb/forum-eos-operation-system:latest}"
APP_PORT="${APP_PORT:-8000}"

say() { printf "\033[1;33m→\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
die() { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is not installed"
docker compose version >/dev/null 2>&1 || die "docker compose plugin is required"

say "Install dir: $INSTALL_DIR"
say "Image:       $IMAGE"
say "App port:    $APP_PORT"

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
mkdir -p backups uploads

random_pw() {
  # 20 url-safe chars
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '=/+' | cut -c1-20
  else
    head -c 32 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-20
  fi
}

if [[ ! -f .env ]]; then
  ADMIN_PW="$(random_pw)"
  DB_PW="$(random_pw)"
  cat > .env <<EOF
# Auto-generated by install.sh — keep this file out of version control.
DATABASE_URL=postgresql://forum:${DB_PW}@db:5432/forum
POSTGRES_USER=forum
POSTGRES_PASSWORD=${DB_PW}
POSTGRES_DB=forum
APP_PORT=${APP_PORT}
ADMIN_PASSWORD=${ADMIN_PW}
EOF
  chmod 600 .env
  ok ".env generated with random passwords"
else
  say ".env already exists — keeping it"
fi

cat > docker-compose.yml <<EOF
services:
  app:
    image: ${IMAGE}
    container_name: forum-app
    ports:
      - "\${APP_PORT:-8000}:8000"
    volumes:
      - ./backups:/app/backups
      - ./uploads:/app/app/static/uploads
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: forum-db
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-forum}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: \${POSTGRES_DB:-forum}
    volumes:
      - forum_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  forum_db_data:
EOF

say "Pulling image..."
docker compose pull

say "Starting containers..."
docker compose up -d

say "Waiting for the app to respond..."
for i in {1..40}; do
  if curl -sf -o /dev/null "http://localhost:${APP_PORT}/"; then
    break
  fi
  sleep 1
done

ADMIN_PW="$(grep '^ADMIN_PASSWORD=' .env | cut -d= -f2-)"

echo
printf '\033[1;32m================================================================\033[0m\n'
ok "Forum OS is running"
echo
echo "  Dashboard:       http://localhost:${APP_PORT}"
echo "  Admin:           http://localhost:${APP_PORT}/admin"
echo "  Admin username:  anything (e.g. admin)"
echo "  Admin password:  ${ADMIN_PW}"
echo
echo "Next steps:"
echo "  1. Visit /admin → set branding + add members."
echo "  2. Put a reverse proxy (Caddy / Cloudflare Tunnel / nginx) in front of port ${APP_PORT} for HTTPS."
echo "  3. Backups are in ${INSTALL_DIR}/backups."
echo
echo "Manage:"
echo "  cd ${INSTALL_DIR} && docker compose logs -f     # tail logs"
echo "  cd ${INSTALL_DIR} && docker compose down        # stop"
echo "  cd ${INSTALL_DIR} && docker compose pull && docker compose up -d   # update"
printf '\033[1;32m================================================================\033[0m\n'
